56 implement action item type maintenance pages
gaepdit/sbeap pull request #109
Opened 2023-07-05 22:33 UTC by tom-karasch

Pages are working fine. Had an issue with one of the API controller Unit Tests

2023-07-05 22:35 UTC, dougwaldron reviewed
![](https://img.shields.io/badge/Accessibility-98-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-90-green?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

![](https://img.shields.io/badge/Accessibility-98-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-92-green?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:https://localhost:7229","mobile:https://localhost:7229"]COMMENT_ID -->

2023-07-14 13:20 UTC, tom-karasch commented
Ready to Review

2023-07-14 20:08 UTC, dougwaldron requested changes
Good work! The pages all work, and I think the depth of unit testing is appropriate. More could be added, but I think it's fine as-is. The one failing test was from a mistyped method name in the API controller. The changes I'm requesting are mostly style consistency issues.

In the future, when creating commits, watch out for unchanged files and character encoding issues. Thanks.

2023-07-14 20:08 UTC, dougwaldron commented on src/AppServices/ActionItemTypes/ActionItemTypeService.cs
> +    private readonly IUserService _users;
Keep a blank line between each method.

2023-07-14 20:10 UTC, dougwaldron commented on src/AppServices/ActionItemTypes/ActionItemTypeService.cs
> +    private readonly IUserService _users;
In case this comment is confusing, the code snippet shown is fine, it's later methods that need to be separated with blank lines. Thanks.

2023-07-18 20:42 UTC, tom-karasch commented on src/AppServices/ActionItemTypes/Permissions/ActionItemTypeOperation.cs
Doug, I based this on the Office Drop downs. In the src/WebApp/Pages/Admin/Maintenance/Offices/Index.cshtml
page it says, **"The “Site Maintenance” role is needed to add or edit Offices. Select an item to edit it. Setting an item as “inactive” makes it unavailable for future use but does not affect any existing use.**" 
However, I do not see anywhere where the permissions are used to limit editing by anyone. So, I added the permissions to add and edit to Site Maintenance Roles Only.  Did I miss something where the page is limited to Site Maintenance?  
I see that the Maintenance index page is available to all Staff in the _MenuPartial.cshtml file. And /Admin/Maintenance can be added to the URL by anyone, so anyone would have access to the Maintenance pages. Or am I missing something?

2023-07-18 20:53 UTC, tom-karasch commented
Doug, 
I just had the one comment above about the Site Maintenance Roles. Shouldn't the AppServices Permissions be added to the Offices, instead of removing them from the Action Item Types? Or should the text on the Offices and Action Item Types Index pages be changed or removed? 
BTW, all tests pass now and the changes are working correctly.

2023-07-18 21:09 UTC, tom-karasch commented
Doug,
It looks like CodeQL is looking for "net70" instead of "net7.0" in the this line from each Project file:
**<TargetFramework>net7.0</TargetFramework>**

2023-07-18 21:37 UTC, tom-karasch commented
Doug,
In regards to my comments about Maintenance Permissions, is that all taken care of in the Razor Page C# code:
**[Authorize(Policy = PolicyName.SiteMaintainer)]**  ?? 
If so, now I see why the AppServices Permissions are unnecessary.

2023-07-19 13:10 UTC, dougwaldron requested changes

2023-07-19 13:10 UTC, dougwaldron commented on src/AppServices/ActionItemTypes/IActionItemTypeService.cs
> +    Task<IReadOnlyList<ListItem>> GetAsync(CancellationToken token = default);
I need one more small fix here: `GetAsync` should be `GetListItemsAsync`. 

It's not spelled out anywhere, but my naming convention goes like this:
"Get" returns a single item (as a DTO).
"Find" returns a single item (as a nullable DTO).
"GetList" -> list of DTO items.
"GetListItems" -> list of "ListItem" types.

2023-07-19 14:25 UTC, dougwaldron commented
> In regards to my comments about Maintenance Permissions, is that all taken care of in the Razor Page C# code: **[Authorize(Policy = PolicyName.SiteMaintainer)]** ?? If so, now I see why the AppServices Permissions are unnecessary.

Right. The `[Authorize]` attribute applies to the whole Razor class, so it's a simpler way to limit access if there's only one permission that applies to the whole page. 

If you need more fine-grained permissions for individual methods or within the cshtml page, that's when the Operations/Permission Handler pattern is useful. But it's not enough to just define them in the Services project, you actually have to include them and use them within the page. 

You can see how to selectively apply a policy in the Cases Index page:

1. Inject the auth service:
https://github.com/gaepdit/sbeap/blob/5e263172ec88cdbe5e9f093c5594af8a56f8bb2e/src/WebApp/Pages/Cases/Index.cshtml.cs#L24-L32

2. Call the `AuthorizeAsync` method as needed and use the result:
https://github.com/gaepdit/sbeap/blob/5e263172ec88cdbe5e9f093c5594af8a56f8bb2e/src/WebApp/Pages/Cases/Index.cshtml.cs#L70-L71

Or in the Cases Details page, you can see how to handle more complex permissions that depend on the specific item being viewed:
https://github.com/gaepdit/sbeap/blob/5e263172ec88cdbe5e9f093c5594af8a56f8bb2e/src/WebApp/Pages/Cases/Details.cshtml.cs#L46

2023-07-20 13:08 UTC, closed without merging