76 implement agency maintenance pages
gaepdit/sbeap pull request #111
Opened 2023-07-07 19:12 UTC by tom-karasch

Pages done. Working on unit tests.  WIP

2023-07-07 21:47 UTC, dougwaldron reviewed
![](https://img.shields.io/badge/Accessibility-98-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-77-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

![](https://img.shields.io/badge/Accessibility-98-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-95-green?style=flat-square) ![](https://img.shields.io/badge/SEO-92-green?style=flat-square) 
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:https://localhost:7229","mobile:https://localhost:7229"]COMMENT_ID -->

2023-07-07 21:56 UTC, tom-karasch commented
Two tests still not working correctly, but feel free to review, Doug

2023-07-17 15:08 UTC, dougwaldron requested changes
Please make the following changes. They are mostly similar to the ones from my Action Item Type review.

Be careful, there's a difference between `GetList`, which returns a list of DTO items, and `GetListItems`, which returns a list of the `ListItem` type. I think that's what was causing the problem on the Case index and edit pages.

2023-07-17 15:08 UTC, dougwaldron commented on src/AppServices/Agencies/IAgencyService.cs
> +    Task<IReadOnlyList<ListItem>> GetActiveListItemsAsync(CancellationToken token = default);
You still need a method to return all Agencies as list items, not just active ones. (The search form needs to be able to search for inactive Agencies as well as active.)

2023-07-18 21:50 UTC, tom-karasch commented on src/AppServices/Agencies/Permissions/AgencyOperation.cs
See my comment from Action Item Types about Permissions for Site Maintenance. If no permissions are used, any user ca add or edit drop down items. Unless the line: 
**[Authorize(Policy = PolicyName.SiteMaintainer)]**
is all that is necessary

2023-07-18 23:20 UTC, tom-karasch commented on src/WebApp/Pages/Cases/Index.cshtml.cs
> +        AgencySelectList = (SelectList)await _agencyService.GetActiveListItemsAsync();
Doug, I am still not able to fix this. I don't understand what is going on here. I made changes that I thought were correct, but still is not working.

2023-07-19 15:48 UTC, tom-karasch commented
Doug,
I think I made all necessary changes including modifying the CaseworkUpdatePermissionsHandler. Not sure if this is correct, but it works now. Also, just wanted to know about my questions: https://github.com/gaepdit/sbeap/pull/111#discussion_r1267336728
https://github.com/gaepdit/sbeap/pull/109#discussion_r1267287599

Are the permissions to edit/add/activate ActionItemTypes and Agencies controlled by the Razor Page syntax ---> 
**[Authorize(Policy = PolicyName.SiteMaintainer)]**
Does this make the AppServices Permissions for ActionItemTypes and Agencies unnecessary?? 

BTW, This pull request will also cover PR#109. So, you should be able to close both by merging this PR.

2023-07-19 18:34 UTC, tom-karasch commented
Made requested changes

2023-07-20 13:51 UTC, dougwaldron commented
SonarCloud analysis failure is due to code duplication between action item types and agencies, which is acceptable.

2023-07-20 13:54 UTC, merged