Feat/site map
gaepdit/sbeap pull request #68
Opened 2023-05-04 13:37 UTC by tom-karasch

Doug,
I think I have this correct now. Does this look like what you are thinking for design of page structure?

2023-05-04 13:38 UTC, dougwaldron reviewed
![](https://img.shields.io/badge/Accessibility-98-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-61-orange?style=flat-square) ![](https://img.shields.io/badge/SEO-88-orange?style=flat-square) 
| Device | URL |
|--|--|
| desktop | https://localhost:7229 |

![](https://img.shields.io/badge/Accessibility-98-green?style=flat-square) ![](https://img.shields.io/badge/Best%20Practices-100-green?style=flat-square) ![](https://img.shields.io/badge/Performance-93-green?style=flat-square) ![](https://img.shields.io/badge/SEO-88-orange?style=flat-square) 
| Device | URL |
|--|--|
| mobile | https://localhost:7229 |

Not what you expected? Are your scores flaky? [Try running on Foo instead](https://github.com/foo-software/lighthouse-check#foos-automated-lighthouse-check-api-usage)
<!-- generated by lighthouse-check -->
<!-- COMMENT_ID["desktop:https://localhost:7229","mobile:https://localhost:7229"]COMMENT_ID -->

2023-05-04 19:05 UTC, dougwaldron requested changes
Please see the attached comments. Thanks.

2023-05-04 19:05 UTC, dougwaldron commented on docs/Site map.md
> +* `/Contact/Details/{id}` (List of Customers handled by a Program Contact)
Remove.

2023-05-04 19:05 UTC, dougwaldron commented on docs/Site map.md
> +* `/Maintenance` (List of Items that can be modified on Site - Action Items and Offices)
There is also an "Agency" maintenance item. See #62.

2023-05-04 19:05 UTC, dougwaldron commented on docs/Site map.md
> +* `/Maintenance/ActionItem/Details/{id}` (Details for Action Item. Links to Edit)
Remove the Details page.

2023-05-04 19:05 UTC, dougwaldron commented on docs/Site map.md
> +* Add Case (Redirect to Add Case Page: `/Case/Add`)
Add Case won't be linked from the menu bar. It's only linked from the Customer page.

2023-05-08 20:07 UTC, tom-karasch commented
I think I made all the correct changes. It is a little different page arrangement than I thought.

2023-05-09 14:36 UTC, merged

2023-05-10 13:35 UTC, tom-karasch reviewed
Sorry, Doug if it was a bit sloppy, or off a bit from your plan of ASP pages. Thanks for sprucing it up!